%% An application that trains a neural network to detect objects using side scan sonar.
allImages = imageDatastore('TrainingData', 'IncludeSubfolders', true,...
'LabelSource', 'foldernames');
%% Split data into training and test sets (80% of images will be set as training; 20% for testing)
[trainingImages, testImages] = splitEachLabel(allImages, 0.8, 'randomize');
alex = alexnet;
layers = alex.Layers;
layers(23) = fullyConnectedLayer(4); % change this based on # of classes
layers(25) = classificationLayer;
trainingImages.ReadFcn = @readFunctionTrain; % resize
testImages.ReadFcn = @readFunctionTrain; % resize
options = trainingOptions('sgdm', ...
'MiniBatchSize',16, ...
'MaxEpochs',10, ...
'InitialLearnRate',1e-4, ...
'Shuffle','every-epoch', ...
'ValidationData', testImages, ...
'ValidationFrequency',3, ...
'Verbose',false, ...
'Plots','training-progress', ExecutionEnvironment="multi-gpu");
bottleDefectNet3 = trainNetwork(trainingImages, layers, options); % train network (takes time)
%% Test Network Performance (find accuracy with test images)
predictedLabels = classify(bottleDefectNet3, testImages); % run network with test images
accuracy = mean(predictedLabels == testImages.Labels) % find avg # correct
confusionchart(predictedLabels, testImages.Labels) % generate confusion matrix
save('bottleDefectNet3.mat', 'bottleDefectNet3')